version: "3.9"

services:
  app:
    build: .
    container_name: gogo-study-app
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://gogo:gogo_pw@db:5432/gogostudy?schema=public"
      REDIS_HOST: gogo-study-redis
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    restart: always

  db:
    image: postgres:16-alpine
    container_name: gogo-study-db
    environment:
      POSTGRES_USER: gogo
      POSTGRES_PASSWORD: gogo_pw
      POSTGRES_DB: gogostudy
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: gogo-study-redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  db-data:
